version: "3"
services:
  # negatiview:
  #   container_name: rust
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - postgres
  #     - redis
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/redis
  kafka:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/kafka
volumes:
  db: {}
